name: bokeh

channels:
  - bokeh
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - notebook
  - bokeh>=1.4
  - pandas
  - scipy
  - selenium
  - datashader
  - networkx
  - flask
  - phantomjs
  - holoviews
  - jupyter_contrib_nbextensions
